import React, { useState, useEffect, useRef } from 'react';
import './Process.css';
import { IoSettingsOutline } from "react-icons/io5";
import { BsWrenchAdjustableCircle } from "react-icons/bs";
import { FaRegHandshake } from "react-icons/fa";
import { motion } from 'framer-motion'; // Import motion

const Process = () => {
    // State to hold the fill percentage for the two progress lines
    const [progress1, setProgress1] = useState(0);
    const [progress2, setProgress2] = useState(0);

    // Refs to get the DOM elements for position calculations
    const timelineRef = useRef(null);
    const point1Ref = useRef(null);
    const point2Ref = useRef(null);
    const point3Ref = useRef(null);

    useEffect(() => {
        const handleScroll = () => {
            if (!point1Ref.current || !point2Ref.current || !point3Ref.current) {
                return;
            }

            // Get the vertical position of each icon point
            const p1Top = point1Ref.current.offsetTop;
            const p2Top = point2Ref.current.offsetTop;
            const p3Top = point3Ref.current.offsetTop;
            
            // Get the timeline container's position relative to the viewport
            const timelineTop = timelineRef.current.getBoundingClientRect().top;
            
            // Calculate scroll position relative to the start of the timeline
            const scrollPosition = window.innerHeight * 0.7 - timelineTop;

            // --- Calculate Progress for the first line ---
            const totalDistance1 = p2Top - p1Top;
            const traveled1 = scrollPosition - p1Top;
            const progressPercentage1 = (traveled1 / totalDistance1) * 100;
            setProgress1(Math.max(0, Math.min(100, progressPercentage1)));

            // --- Calculate Progress for the second line ---
            const totalDistance2 = p3Top - p2Top;
            const traveled2 = scrollPosition - p2Top;
            const progressPercentage2 = (traveled2 / totalDistance2) * 100;
            setProgress2(Math.max(0, Math.min(100, progressPercentage2)));
        };

        window.addEventListener('scroll', handleScroll);
        // Initial call to set state on load
        handleScroll();

        // Cleanup listener on component unmount
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const steps = [
        {
            icon: <IoSettingsOutline size={24} />,
            title: "Effortless Setup",
            description: "We handle the entire setup, starting with a detailed safety evaluation of your premises. A certified electrician performs the installation to meet all safety standards. A Tranga representative will then walk you through the machine's operation.",
            ref: point1Ref,
        },
        {
            icon: <BsWrenchAdjustableCircle size={24} />,
            title: "Worry-Free Servicing",
            description: "All upkeep is on us. We conduct regular servicing, restock fragrances, and handle any necessary repairs, giving you complete peace of mind. No effort is required from your side.",
            ref: point2Ref,
        },
        {
            icon: <FaRegHandshake size={24} />,
            title: "Equitable Profit Sharing",
            description: "There are no upfront costs for your establishment. Tranga manages all installation, refilling, and maintenance expenses. In return, we simply split the revenue generated by the machine with you.",
            ref: point3Ref,
        },
    ];

    return (
        <section className="process-section ">
            <motion.div 
                className="process-content"
                initial={{ opacity: 0, x: -50 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.8, ease: "easeOut" }}
                viewport={{ once: true }}
            >
                <h2 className="process-title">
                    Our Partnership Model: Zero Risk, All Reward for Your Venue
                </h2>
                <p className="process-subtitle">
                    Our partner venues typically generate an average of £32,860 in revenue over a three-year term.
                </p>
                <button className="process-button">Get in Touch</button>
            </motion.div>

            <div className="process-timeline" ref={timelineRef}>
                {/* --- Static background lines --- */}
                <div className="timeline-line-bg" style={{ top: point1Ref.current?.offsetTop, height: point2Ref.current && point1Ref.current ? point2Ref.current.offsetTop - point1Ref.current.offsetTop : 0 }} />
                <div className="timeline-line-bg" style={{ top: point2Ref.current?.offsetTop, height: point3Ref.current && point2Ref.current ? point3Ref.current.offsetTop - point2Ref.current.offsetTop : 0 }} />
                
                {/* --- Dynamic progress lines --- */}
                <div className="timeline-line-progress" style={{ top: point1Ref.current?.offsetTop, height: point2Ref.current && point1Ref.current ? (point2Ref.current.offsetTop - point1Ref.current.offsetTop) * (progress1 / 100) : 0 }} />
                <div className="timeline-line-progress" style={{ top: point2Ref.current?.offsetTop, height: point3Ref.current && point2Ref.current ? (point3Ref.current.offsetTop - point2Ref.current.offsetTop) * (progress2 / 100) : 0 }} />

                {steps.map((step, index) => (
                    <div className="timeline-item" key={index} ref={step.ref}>
                        <div className="timeline-icon-container">
                            <div className={`timeline-icon icon-${index + 1}`}>
                                {step.icon}
                            </div>
                        </div>
                        <div className="timeline-text-content">
                            <h3 className="timeline-item-title">{step.title}</h3>
                            <p className="timeline-item-description">{step.description}</p>
                        </div>
                    </div>
                ))}
            </div>
        </section>
    );
};

export default Process;